(() => {
  const data = window.KUNSHAN_DATA;
  const items = data.fragments, relations = data.relations;
  const byId = new Map(items.map(item => [item.id, item]));
  const sources = new Map(data.sources.map(source => [source.id, source]));
  const categories = [
    {id:'Places', color:'#b85c3f', icon:'⌂', emoji:'🏮'},
    {id:'Artifacts', color:'#395f9a', icon:'◇', emoji:'🏺'},
    {id:'Food', color:'#d87932', icon:'◒', emoji:'🍜'},
    {id:'Traditions', color:'#6e5aa4', icon:'◎', emoji:'🎭'},
    {id:'Stories', color:'#a26842', icon:'✦', emoji:'📜'}
  ];
  const categoryById = new Map(categories.map(c => [c.id,c]));
  const copy = {
    en: {title:'Kunshan Cultural Map',subtitle:'Explore culture, place by place',search:'Search names, descriptions, or towns',categories:'Categories',clear:'Clear',discoveries:'cultural records',surprise:'Surprise me',map:'Map',patterns:'Patterns',mapLabel:'Kunshan · Cultural discovery',mapHint:'Drag to explore · Scroll or use controls to zoom',empty:'No matching records. Clear filters or try another search.',detailTitle:'Start exploring from the map',detailEmpty:'Select a record to read its source, location precision, and cultural connections.',practical:'Location and evidence',save:'＋ Add to route',saved:'✓ Added to route',unroutable:'Area anchor · route unavailable',route:'My cultural route',savedPlaces:n=>`${n} saved specific site${n===1?'':'s'}`,routeEmpty:'Add specific-site records to create a schematic route.',generate:'Generate schematic route',routeSummary:n=>`${n} stops · straight-line sequence, not navigation`,remove:'Remove',source:'Sources',precision:'Coordinate precision',related:'Related records',noRelated:'No documented link in this dataset',view:'View source',mapAria:'Interactive Kunshan map',patternsTitle:'Cultural patterns',patternsIntro:'82 curated records and 67 evidence-linked relations. This is a sample, not a complete census.',chartTitle:'Records by category',chartHint:'Click a bar to isolate a category; click it again to show all.',networkTitle:'Evidence-linked cultural network',networkHint:'Showing the most connected records. Select any record to see its immediate links. Lines are cultural relations, not roads.',networkAria:'Network of sourced cultural relations',networkCount:(nodes,edges)=>`${nodes} nodes · ${edges} visible links of ${relations.length} total`,categoriesNames:{Places:'Places',Artifacts:'Artifacts',Food:'Food',Traditions:'Traditions',Stories:'Stories'},precisionNames:{'specific-site':'Specific site','town-area anchor':'Town area anchor','town anchor':'Town anchor','associated-site anchor':'Associated site anchor','district anchor':'District anchor','city anchor':'City anchor','regional food anchor':'Regional food anchor','landscape anchor':'Landscape anchor','village-area anchor':'Village area anchor','city cultural anchor':'City cultural anchor','regional anchor':'Regional anchor'}},
    zh: {title:'昆山文化地图',subtitle:'一处一处，探索昆山文化',search:'搜索名称、英文介绍或乡镇',categories:'文化类别',clear:'清除',discoveries:'条文化记录',surprise:'随机发现一处文化',map:'地图',patterns:'文化关联',mapLabel:'昆山市 · 文化探索',mapHint:'拖动地图以探索 · 滚轮或按钮缩放',empty:'没有匹配项，请清除筛选或更换关键词。',detailTitle:'从地图开始探索',detailEmpty:'点击记录查看来源、坐标精度和文化关联。',practical:'位置与证据',save:'＋ 加入路线',saved:'✓ 已加入路线',unroutable:'区域锚点 · 不支持路线',route:'我的文化路线',savedPlaces:n=>`${n} 个精确地点`,routeEmpty:'选择标为“精确地点”的记录，可生成示意路线。',generate:'生成示意路线',routeSummary:n=>`${n} 站 · 直线连接，不能用于导航`,remove:'移除',source:'资料来源',precision:'坐标精度',related:'相关记录',noRelated:'数据集中暂无关联',view:'查看来源',mapAria:'昆山交互地图',patternsTitle:'昆山文化关联',patternsIntro:'82 条精选记录和 67 条有来源的关联；不是昆山文化资源的完整名录。',chartTitle:'各类别记录数量',chartHint:'点击条形单独筛选，再次点击恢复全部。',networkTitle:'有来源的文化关联网络',networkHint:'默认显示关联最多的记录。选择任意记录可查看直接关联；连线不代表道路。',networkAria:'有来源的昆山文化关联网络',networkCount:(nodes,edges)=>`当前 ${nodes} 个节点、${edges} 条连线；全部 ${relations.length} 条`,categoriesNames:{Places:'文化地点',Artifacts:'文化物件',Food:'地方美食',Traditions:'传统技艺',Stories:'文化故事'},precisionNames:{'specific-site':'精确地点','town-area anchor':'乡镇范围锚点','town anchor':'乡镇锚点','associated-site anchor':'关联地点锚点','district anchor':'区级锚点','city anchor':'市级锚点','regional food anchor':'区域美食锚点','landscape anchor':'景观锚点','village-area anchor':'村落范围锚点','city cultural anchor':'市级文化锚点','regional anchor':'区域锚点'}}
  };
  const $ = id => document.getElementById(id);
  const stored = (() => {try{return localStorage.getItem('kunshan-map-language')}catch{return null}})();
  const state = {language:stored==='zh'?'zh':'en',active:new Set(categories.map(c=>c.id)),query:'',selected:null,saved:[],route:[],view:'map'};
  const t = () => copy[state.language];
  const name = item => state.language==='zh'?item.nameZh:item.name;
  const escapeHtml = value => String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const precision = item => t().precisionNames[item.locationPrecision] || item.locationPrecision;
  const connected = id => relations.filter(r=>r.a===id || r.b===id);
  const matches = () => items.filter(i=>state.active.has(i.category) && [i.name,i.nameZh,i.summary,i.town,i.area].join(' ').toLowerCase().includes(state.query.toLowerCase()));
  const map = L.map('mapViewport',{center:[31.29,120.94],zoom:11,zoomControl:false,preferCanvas:true});
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,minZoom:9,noWrap:true,keepBuffer:0,updateWhenIdle:true,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
  const markerLayer=L.layerGroup().addTo(map), routeLayer=L.layerGroup().addTo(map);
  const icon = (i,selected) => L.divIcon({className:'cultural-marker-wrap',html:`<span class="cultural-marker ${selected?'is-selected':''}" style="--marker:${categoryById.get(i.category).color}"><b>${categoryById.get(i.category).emoji}</b></span>`,iconSize:selected?[48,48]:[40,40],iconAnchor:selected?[24,24]:[20,20]});
  const radians=Math.PI/180;
  const distance=(a,b)=>{const dlat=(b.lat-a.lat)*radians,dlng=(b.lng-a.lng)*radians,q=Math.sin(dlat/2)**2+Math.cos(a.lat*radians)*Math.cos(b.lat*radians)*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
  function renderFilters(){ $('categoryFilters').innerHTML=categories.map(c=>`<button type="button" class="filter ${state.active.has(c.id)?'active':''}" data-category="${c.id}" style="--category:${c.color}" aria-pressed="${state.active.has(c.id)}"><span>${c.icon}</span>${t().categoriesNames[c.id]}<b>${items.filter(i=>i.category===c.id).length}</b></button>`).join(''); }
  function renderList(){const found=matches();$('resultCount').textContent=found.length;$('itemList').innerHTML=found.length?found.map(i=>`<button type="button" class="item-card ${state.selected===i.id?'selected':''}" data-id="${i.id}"><span class="item-icon" style="background:${categoryById.get(i.category).color}18;color:${categoryById.get(i.category).color}">${categoryById.get(i.category).emoji}</span><span><strong>${escapeHtml(name(i))}</strong><small>${t().categoriesNames[i.category]} · ${escapeHtml(i.town)}</small><em>${escapeHtml(precision(i))}</em></span><i>›</i></button>`).join(''):`<div class="empty">${t().empty}</div>`;}
  function renderMarkers(){markerLayer.clearLayers();matches().forEach(i=>L.marker([i.lat,i.lng],{icon:icon(i,state.selected===i.id),title:name(i),alt:name(i),keyboard:true,riseOnHover:true}).on('click',()=>select(i.id)).addTo(markerLayer));}
  function renderDetails(){const i=byId.get(state.selected),panel=$('detailPanel');if(!i){panel.innerHTML=`<div class="detail-empty"><span>⌖</span><h2>${t().detailTitle}</h2><p>${t().detailEmpty}</p></div>`;return;}
    const c=categoryById.get(i.category),links=connected(i.id),routable=i.locationPrecision==='specific-site';
    const sourceLinks=i.sourceIds.map(id=>sources.get(id)).filter(Boolean).map(s=>`<a href="${escapeHtml(s.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(s.publisher)} · ${escapeHtml(s.title)}</a>`).join('');
    panel.innerHTML=`<div class="detail-top"><span class="category-chip" style="--category:${c.color}">${t().categoriesNames[i.category]}</span><button id="closeDetail" aria-label="Close">×</button></div><div class="detail-hero" style="--hero:${c.color}"><span>${c.emoji}</span><small>${escapeHtml(i.area)}</small></div><div class="detail-content"><h1>${escapeHtml(name(i))}</h1><p>${escapeHtml(i.summary)}</p><div class="practical"><span>⌖</span><div><b>${t().practical}</b><small>${escapeHtml(i.town)} · ${t().precision}: ${escapeHtml(precision(i))}</small></div></div><div class="evidence"><b>${t().source}</b>${sourceLinks}</div><div class="relations"><b>${t().related} (${links.length})</b>${links.length?links.map(r=>{const other=byId.get(r.a===i.id?r.b:r.a);return `<button type="button" data-related="${other.id}">${escapeHtml(name(other))} <small>${escapeHtml(r.label)} · ${r.sourceIds.length} source(s)</small></button>`}).join(''):`<p>${t().noRelated}</p>`}</div><button id="saveButton" class="save-button ${state.saved.includes(i.id)?'saved':''}" ${routable?'':'disabled'}>${routable?(state.saved.includes(i.id)?t().saved:t().save):t().unroutable}</button></div>`;
    $('closeDetail').onclick=()=>select(null);$('saveButton').onclick=()=>toggleSave(i.id);
    panel.querySelectorAll('[data-related]').forEach(button=>button.onclick=()=>select(button.dataset.related,true));
  }
  function select(id,focus=false){state.selected=byId.has(id)?id:null;renderDetails();renderList();renderMarkers();renderPatterns();if(focus&&state.selected){setView('map');const i=byId.get(id);map.flyTo([i.lat,i.lng],14,{duration:.6})}}
  function toggleSave(id){const i=byId.get(id);if(!i||i.locationPrecision!=='specific-site')return;const index=state.saved.indexOf(id);if(index>=0){state.saved.splice(index,1);state.route=state.route.filter(x=>x!==id)}else state.saved.push(id);renderDetails();renderRoute();renderRouteLine()}
  function renderRoute(){const route=state.route.map(id=>byId.get(id));$('routePanel').innerHTML=`<div class="route-head"><div><span>${t().route}</span><strong>${t().savedPlaces(state.saved.length)}</strong></div></div><div class="route-body"><div class="saved-stops">${state.saved.length?state.saved.map((id,n)=>`<div class="saved-stop" draggable="true" data-saved="${id}"><b>${n+1}</b><span>${escapeHtml(name(byId.get(id)))}</span><button data-remove="${id}" aria-label="${t().remove} ${escapeHtml(name(byId.get(id)))}">×</button></div>`).join(''):`<p class="route-empty">${t().routeEmpty}</p>`}</div><button id="generateRoute" class="generate" ${state.saved.length<2?'disabled':''}>${t().generate} →</button>${route.length?`<div class="route-result"><b>${t().routeSummary(route.length)}</b><p>${route.map((i,n)=>`${n+1}. ${escapeHtml(name(i))}`).join(' → ')}</p></div>`:''}</div>`;
    $('routePanel').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>toggleSave(b.dataset.remove));$('generateRoute').onclick=generateRoute;
    let dragged=null;$('routePanel').querySelectorAll('[data-saved]').forEach(el=>{el.ondragstart=()=>{dragged=el.dataset.saved};el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();if(!dragged||dragged===el.dataset.saved)return;const from=state.saved.indexOf(dragged),to=state.saved.indexOf(el.dataset.saved);state.saved.splice(from,1);state.saved.splice(to,0,dragged);state.route=[];renderRoute();renderRouteLine()}});
  }
  function generateRoute(){const remaining=state.saved.map(id=>byId.get(id));if(remaining.length<2)return;const ordered=[remaining.shift()];while(remaining.length){remaining.sort((a,b)=>distance(ordered.at(-1),a)-distance(ordered.at(-1),b));ordered.push(remaining.shift())}state.route=ordered.map(i=>i.id);renderRoute();renderRouteLine()}
  function renderRouteLine(){routeLayer.clearLayers();const route=state.route.map(id=>byId.get(id));if(route.length<2)return;L.polyline(route.map(i=>[i.lat,i.lng]),{color:'#d94f42',weight:5,dashArray:'10 7'}).addTo(routeLayer);route.forEach((i,n)=>L.marker([i.lat,i.lng],{interactive:false,icon:L.divIcon({className:'route-stop-wrap',html:`<span class="route-stop">${n+1}</span>`,iconSize:[24,24],iconAnchor:[12,12]})}).addTo(routeLayer))}
  function networkSubset(){let ids;if(state.selected){const neighbors=connected(state.selected).map(r=>r.a===state.selected?r.b:r.a);ids=[state.selected,...neighbors].slice(0,24)}else{const degree=new Map(items.map(i=>[i.id,connected(i.id).length]));ids=items.filter(i=>state.active.has(i.category)).sort((a,b)=>degree.get(b.id)-degree.get(a.id)).slice(0,20).map(i=>i.id)}return {ids,edges:relations.filter(r=>ids.includes(r.a)&&ids.includes(r.b))}}
  function renderPatterns(){const max=Math.max(...categories.map(c=>items.filter(i=>i.category===c.id).length));$('categoryChart').innerHTML=categories.map(c=>{const n=items.filter(i=>i.category===c.id).length;return `<button type="button" class="chart-row ${state.active.has(c.id)?'active':''}" data-chart-category="${c.id}" aria-pressed="${state.active.has(c.id)}"><span>${t().categoriesNames[c.id]}</span><span class="chart-track"><span style="width:${n/max*100}%;background:${c.color}"></span></span><b>${n}</b></button>`}).join('');
    const {ids,edges}=networkSubset(),positions=new Map(ids.map((id,n)=>[id,{x:300+210*Math.cos(2*Math.PI*n/ids.length-Math.PI/2),y:190+128*Math.sin(2*Math.PI*n/ids.length-Math.PI/2)}]));
    $('networkGraph').innerHTML=edges.map(r=>{const a=positions.get(r.a),b=positions.get(r.b);return `<line class="network-edge" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"><title>${escapeHtml(r.label)} · ${r.sourceIds.length} source(s)</title></line>`}).join('')+ids.map(id=>{const i=byId.get(id),p=positions.get(id);return `<g class="network-node ${state.selected===id?'selected':''}" data-node="${id}" tabindex="0" role="button" aria-label="${escapeHtml(name(i))}" transform="translate(${p.x},${p.y})"><circle r="17" fill="${categoryById.get(i.category).color}"/><text class="node-icon" text-anchor="middle" dominant-baseline="central">${categoryById.get(i.category).emoji}</text><text class="node-label" text-anchor="middle" y="31">${escapeHtml(name(i).slice(0,12))}</text><title>${escapeHtml(name(i))}</title></g>`}).join('');$('networkLegend').textContent=t().networkCount(ids.length,edges.length);
  }
  function setView(view){state.view=view;const visible=view==='patterns';$('patternsPanel').hidden=!visible;$('mapViewButton').setAttribute('aria-pressed',String(!visible));$('patternsViewButton').setAttribute('aria-pressed',String(visible));if(!visible)requestAnimationFrame(()=>map.invalidateSize())}
  function refresh(){renderFilters();renderList();renderMarkers();renderPatterns()}
  function setLanguage(language){state.language=language;try{localStorage.setItem('kunshan-map-language',language)}catch{}document.documentElement.lang=language==='zh'?'zh-CN':'en';document.title=t().title;$('brandTitle').textContent=t().title;$('brandSubtitle').textContent=t().subtitle;$('searchInput').placeholder=t().search;$('categoryHeading').textContent=t().categories;$('clearFilters').textContent=t().clear;$('resultLabel').textContent=t().discoveries;$('surpriseButton').innerHTML=`<span>✦</span> ${t().surprise}`;$('mapLabel').innerHTML=`<i></i> ${t().mapLabel}`;$('mapHint').textContent=t().mapHint;$('mapViewport').setAttribute('aria-label',t().mapAria);$('mapViewButton').textContent=t().map;$('patternsViewButton').textContent=t().patterns;$('patternsTitle').textContent=t().patternsTitle;$('patternsIntro').textContent=t().patternsIntro;$('chartTitle').textContent=t().chartTitle;$('chartHint').textContent=t().chartHint;$('networkTitle').textContent=t().networkTitle;$('networkHint').textContent=t().networkHint;$('networkGraph').setAttribute('aria-label',t().networkAria);document.querySelectorAll('[data-language]').forEach(b=>{b.classList.toggle('active',b.dataset.language===language);b.setAttribute('aria-pressed',String(b.dataset.language===language))});refresh();renderDetails();renderRoute()}
  $('categoryFilters').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;state.active.has(b.dataset.category)?state.active.delete(b.dataset.category):state.active.add(b.dataset.category);refresh()};
  $('categoryChart').onclick=e=>{const b=e.target.closest('[data-chart-category]');if(!b)return;const id=b.dataset.chartCategory;state.active=new Set(state.active.size===1&&state.active.has(id)?categories.map(c=>c.id):[id]);refresh()};
  $('itemList').onclick=e=>{const b=e.target.closest('[data-id]');if(b)select(b.dataset.id,true)};
  $('networkGraph').onclick=e=>{const n=e.target.closest('[data-node]');if(n)select(n.dataset.node)};
  $('networkGraph').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){const n=e.target.closest('[data-node]');if(n){e.preventDefault();select(n.dataset.node)}}};
  $('searchInput').oninput=e=>{state.query=e.target.value;refresh()};$('clearFilters').onclick=()=>{state.query='';$('searchInput').value='';state.active=new Set(categories.map(c=>c.id));refresh()};
  $('surpriseButton').onclick=()=>{const found=matches();if(found.length)select(found[Math.floor(Math.random()*found.length)].id,true)};
  document.querySelector('.language-toggle').onclick=e=>{const b=e.target.closest('[data-language]');if(b)setLanguage(b.dataset.language)};
  $('mapViewButton').onclick=()=>setView('map');$('patternsViewButton').onclick=()=>setView('patterns');
  $('zoomIn').onclick=()=>map.zoomIn();$('zoomOut').onclick=()=>map.zoomOut();$('resetMap').onclick=()=>map.setView([31.29,120.94],11);
  setLanguage(state.language);requestAnimationFrame(()=>map.invalidateSize());
})();
