window.KUNSHAN_ITEMS = [
  {id:'zhouzhuang',category:'places',lat:31.1179,lng:120.8464,image:'🏮',color:'#b85c3f',duration:150,nameEn:'Zhouzhuang Water Town',nameZh:'周庄古镇',descriptionEn:'Walk beside the Twin Bridges and water lanes to experience the living texture of a Jiangnan water town.',descriptionZh:'沿着双桥与水巷慢行，感受江南水乡延续数百年的生活纹理。',infoEn:'Allow 2–3 hours · Quanfu Road, Zhouzhuang',infoZh:'建议停留 2–3 小时 · 周庄镇全福路',tagsEn:['water town','canals','heritage'],tagsZh:['古镇','水乡','建筑']},
  {id:'kunqu',category:'traditions',lat:31.3825,lng:120.9884,image:'🎭',color:'#6e5aa4',duration:60,nameEn:'Kunqu Opera Museum',nameZh:'昆曲博物馆',descriptionEn:'Hear the music, costumes, and stage stories of Kunqu, one of Kunshan’s most celebrated intangible traditions.',descriptionZh:'聆听“百戏之祖”昆曲的唱腔、服饰与舞台故事，认识昆山最具代表性的非遗。',infoEn:'Allow 60 minutes · Yushan Town',infoZh:'建议停留 60 分钟 · 玉山镇',tagsEn:['Kunqu','intangible heritage','opera'],tagsZh:['昆曲','非遗','戏曲']},
  {id:'tinglin',category:'places',lat:31.3839,lng:120.9813,image:'⛰️',color:'#28746b',duration:90,nameEn:'Tinglin Garden',nameZh:'亭林园',descriptionEn:'A city garden around Mount Yufeng, where memories of Gu Yanwu and Gui Youguang sit among the hills and water.',descriptionZh:'以玉峰山为中心的城市园林，顾炎武、归有光等文化记忆散落于山水之间。',infoEn:'Allow 90 minutes · Ma’anshan Middle Road',infoZh:'建议停留 90 分钟 · 马鞍山中路',tagsEn:['garden','Yushan','literati'],tagsZh:['园林','玉山','名人']},
  {id:'bacon',category:'food',lat:31.4615,lng:120.9353,image:'🦀',color:'#d87932',duration:75,nameEn:'Bacheng Yangcheng Lake Crab',nameZh:'巴城阳澄湖大闸蟹',descriptionEn:'An autumn classic. Bacheng’s network of lakes and canals shaped a distinct seasonal crab culture.',descriptionZh:'秋日里最有名的昆山味道。巴城以水网与蟹文化，形成独特的时令饮食传统。',infoEn:'Best season: Sep–Nov · Bacheng Town',infoZh:'最佳品尝：9–11 月 · 巴城镇',tagsEn:['hairy crab','seasonal','lake food'],tagsZh:['大闸蟹','时令','湖鲜']},
  {id:'jinxi',category:'places',lat:31.2581,lng:120.9466,image:'🛶',color:'#b85c3f',duration:120,nameEn:'Jinxi Water Town',nameZh:'锦溪古镇',descriptionEn:'Ancient bridges, lakes, and old streets come together in a quieter, more intimate water-town rhythm.',descriptionZh:'古桥、湖泊与老街相依。这里保留了安静、细腻的江南水乡日常。',infoEn:'Allow 2 hours · Jinxi Town',infoZh:'建议停留 2 小时 · 锦溪镇',tagsEn:['water town','bridges','canals'],tagsZh:['古镇','古桥','水乡']},
  {id:'gu',category:'people',lat:31.2793,lng:121.0145,image:'📜',color:'#395f9a',duration:45,nameEn:'Gu Yanwu Residence',nameZh:'顾炎武故居',descriptionEn:'Visit the hometown of scholar Gu Yanwu and explore the ideas behind his enduring civic spirit.',descriptionZh:'走进思想家顾炎武的故里，了解“天下兴亡，匹夫有责”背后的学术与家国情怀。',infoEn:'Allow 45 minutes · Qiandeng Town',infoZh:'建议停留 45 分钟 · 千灯镇',tagsEn:['Gu Yanwu','ideas','residence'],tagsZh:['顾炎武','思想','故居']},
  {id:'qiandeng',category:'stories',lat:31.2742,lng:121.0088,image:'🏯',color:'#a26842',duration:120,nameEn:'Qiandeng Water Town',nameZh:'千灯古镇',descriptionEn:'Named for a thousand lights, this old town connects the stories of Gu Yanwu, Kunqu, and water-town trade.',descriptionZh:'相传因千盏灯火而得名。古镇的石板路串起顾炎武、昆曲与水乡商贸的故事。',infoEn:'Allow 2 hours · Qiandeng Town',infoZh:'建议停留 2 小时 · 千灯镇',tagsEn:['stories','water town','lanterns'],tagsZh:['故事','古镇','灯火']},
  {id:'aofeng',category:'food',lat:31.3871,lng:120.9897,image:'🍜',color:'#d87932',duration:45,nameEn:'Aozhao Noodle Craft',nameZh:'奥灶面制作技艺',descriptionEn:'Fine noodles with red-oil fish or duck broth preserve a memorable piece of Kunshan’s everyday taste.',descriptionZh:'红油爆鱼、白汤卤鸭与细面交织，是昆山人用一碗面保存下来的城市味觉。',infoEn:'Allow 45 minutes · Yushan Town',infoZh:'建议用餐 45 分钟 · 玉山镇',tagsEn:['noodles','intangible heritage','local taste'],tagsZh:['面食','非遗','地方味']},
  {id:'sanbao',category:'traditions',lat:31.3766,lng:120.9740,image:'💠',color:'#6e5aa4',duration:40,nameEn:'Kun Stone & the Three Treasures',nameZh:'昆石与三宝',descriptionEn:'Kun stone, Qionghua blossoms, and twin lotus are known as Kunshan’s Three Treasures. Look closely at the stone’s delicate forms.',descriptionZh:'昆石、琼花、并蒂莲被称为“昆山三宝”。细赏昆石玲珑剔透的自然之美。',infoEn:'Allow 40 minutes · Kunshan Cultural Centre',infoZh:'建议停留 40 分钟 · 昆山文化馆',tagsEn:['Kun stone','three treasures','craft'],tagsZh:['昆石','三宝','工艺']},
  {id:'zhaoling',category:'stories',lat:31.4040,lng:120.9508,image:'🏺',color:'#a26842',duration:50,nameEn:'Zhaolingshan Archaeological Site',nameZh:'赵陵山遗址',descriptionEn:'This Neolithic site reveals early settlement and daily life in the Taihu basin—the deeper time layer of Kunshan.',descriptionZh:'新石器时代遗址揭示了太湖流域早期居民的聚落与生活，是昆山更久远的时间刻度。',infoEn:'Allow 50 minutes · Development Zone',infoZh:'建议停留 50 分钟 · 开发区',tagsEn:['archaeology','site','prehistory'],tagsZh:['考古','遗址','史前']},
  {id:'gujian',category:'people',lat:31.3810,lng:120.9937,image:'🖋️',color:'#395f9a',duration:45,nameEn:'Gui Youguang Memorial Hall',nameZh:'归有光纪念馆',descriptionEn:'Meet the writer and educator Gui Youguang, whose work and teaching left a lasting mark on Kunshan.',descriptionZh:'“唐宋派”代表归有光长期生活于昆山，他的文章与教育影响仍在这片土地延续。',infoEn:'Allow 45 minutes · Yushan Town',infoZh:'建议停留 45 分钟 · 玉山镇',tagsEn:['Gui Youguang','literature','education'],tagsZh:['归有光','文学','教育']},
  {id:'dragon',category:'traditions',lat:31.1215,lng:120.8519,image:'🚣',color:'#6e5aa4',duration:50,nameEn:'Zhouzhuang Fast Boat Tradition',nameZh:'周庄摇快船',descriptionEn:'Driven by paddles, chants, and shared rhythm, this water race carries the memory of canal life and teamwork.',descriptionZh:'以船桨、号子和默契节奏驱动的水上竞技，承载水乡人对河道与团结的记忆。',infoEn:'Festival activity · Zhouzhuang Town',infoZh:'节庆活动为主 · 周庄镇',tagsEn:['fast boats','folk custom','water town'],tagsZh:['快船','民俗','水乡']}
];
window.CATEGORIES = [
  {id:'places',icon:'⌂',color:'#b85c3f'}, {id:'stories',icon:'✦',color:'#a26842'}, {id:'traditions',icon:'◎',color:'#6e5aa4'}, {id:'food',icon:'◒',color:'#d87932'}, {id:'people',icon:'♙',color:'#395f9a'}
];
